import React from "react";
import {
  LayoutDashboard,
  Wallet,
  Receipt,
  Wallet2,
  FileText,
  PlusCircle,
  Truck,
  RotateCcw,
  Clock,
  Banknote,
  Users,
  UserCircle,
  Package,
  Wrench,
  Settings,
  FileBarChart,
  ArrowRightLeft,
  ShoppingCart,
  Scissors,
  Bell,
  Search,
  KeyRound,
  Building2,
  Factory,
  List,
  ShieldEllipsis,
  CircleHelp,
  Crown,
  Tags,
  FolderTree,
  Calculator,
  BarChart3,
  Gift,
} from "lucide-react";

const iconSize = 20;
const createIcon = (Icon: React.ComponentType<{ size?: number; className?: string }>, size = iconSize) =>
  React.createElement(Icon, { size, className: "shrink-0 text-current" });

export type SidebarLabel = {
  icon: string | null;
  label: string;
  path: string;
  level: number;
  subItems?: SidebarLabel[];
  permission?: string;
  permissions?: string[];
  iconComponent?: React.ReactNode | null;
  section?: string;
};

export const sidebarLabels: SidebarLabel[] = [
  {
    icon: null,
    label: "لوحة التحكم",
    path: "/dashboard",
    level: 1,
    section: "الرئيسية",
    iconComponent: createIcon(LayoutDashboard),
  },
  {
    icon: null,
    label: "إدارة الحسابات",
    path: "/payments",
    level: 1,
    section: "المالية",
    permissions: ["payments.view", "expenses.view"],
    iconComponent: createIcon(Wallet),
    subItems: [
      {
        icon: null,
        label: "قائمة المدفوعات",
        path: "/payments",
        level: 2,
        permissions: ["payments.view"],
        iconComponent: createIcon(Receipt),
      },
      {
        icon: null,
        label: "قائمة المصروفات",
        path: "/expenses",
        level: 2,
        permissions: ["expenses.view"],
        iconComponent: createIcon(Wallet2),
      },
    ],
  },
  {
    icon: null,
    label: "الخزنة",
    path: "/cashboxes",
    level: 1,
    section: "المالية",
    permissions: ["cashboxes.view"],
    iconComponent: createIcon(Banknote),
    subItems: [
      {
        icon: null,
        label: "الخزنة",
        path: "/cashboxes",
        level: 2,
        permissions: ["cashboxes.view"],
        iconComponent: createIcon(Banknote),
      },
      {
        icon: null,
        label: "كشف المعاملات",
        path: "/cashboxes/transactions",
        level: 2,
        permissions: ["cashboxes.view"],
        iconComponent: createIcon(ArrowRightLeft),
      },
      {
        icon: null,
        label: "القيود المحاسبية",
        path: "/treasury/entries",
        level: 2,
        permissions: ["accounting.view"],
        iconComponent: createIcon(FileText),
      },
    ],
  },
  {
    icon: null,
    label: "قسم البيع",
    path: "/sales",
    level: 1,
    section: "العمليات",
    iconComponent: createIcon(ShoppingCart),
    subItems: [
      {
        icon: null,
        label: "فواتير البيع",
        path: "/sales/invoices",
        level: 2,
        iconComponent: createIcon(FileText),
      },
      {
        icon: null,
        label: "إنشاء فاتورة بيع",
        path: "/sales/create",
        level: 2,
        iconComponent: createIcon(PlusCircle),
      },
      {
        icon: null,
        label: "تقارير المبيعات",
        path: "/sales/reports",
        level: 2,
        iconComponent: createIcon(FileBarChart),
      },
    ],
  },
  {
    icon: null,
    label: "قسم التفصيل",
    path: "/tailoring",
    level: 1,
    section: "العمليات",
    iconComponent: createIcon(Scissors),
    subItems: [
      {
        icon: null,
        label: "أوامر التفصيل",
        path: "/tailoring/orders",
        level: 2,
        iconComponent: createIcon(Scissors),
      },
      {
        icon: null,
        label: "تسليمات التفصيل",
        path: "/tailoring/deliveries",
        level: 2,
        iconComponent: createIcon(Gift),
      },
    ],
  },
  {
    icon: null,
    label: "قسم الإيجار",
    path: "/orders/list",
    level: 1,
    section: "العمليات",
    permissions: ["invoices.view"],
    iconComponent: createIcon(KeyRound),
  },
  {
    icon: null,
    label: "التسليمات",
    path: "/deliveries",
    level: 1,
    section: "العمليات",
    permissions: ["invoice_delivery.view"],
    iconComponent: createIcon(Truck),
    subItems: [
      {
        icon: null,
        label: "تسليمات الفواتير",
        path: "/deliveries",
        level: 2,
        permissions: ["invoice_delivery.view"],
        iconComponent: createIcon(Truck),
      },
      {
        icon: null,
        label: "بحث التسليمات والإرجاعات",
        path: "/orders/search-deliveries-returns",
        level: 2,
        iconComponent: createIcon(Search),
      },
      {
        icon: null,
        label: "إرجاعات الفواتير",
        path: "/returns",
        level: 2,
        permissions: ["invoice_delivery.view"],
        iconComponent: createIcon(RotateCcw),
      },
      {
        icon: null,
        label: "الإرجاعات المتأخرة",
        path: "/overdue-returns",
        level: 2,
        permissions: ["invoice_delivery.view"],
        iconComponent: createIcon(Clock),
      },
    ],
  },
  {
    icon: null,
    label: "العملاء",
    path: "/customers",
    level: 1,
    section: "الإدارة",
    permissions: ["customers.view"],
    iconComponent: createIcon(Users),
  },
  {
    icon: null,
    label: "الموظفين",
    path: "/employees",
    level: 1,
    section: "الإدارة",
    iconComponent: createIcon(UserCircle),
    subItems: [
      {
        icon: null,
        label: "قائمة الموظفين",
        path: "/employees",
        level: 2,
        iconComponent: createIcon(List),
      },
      {
        icon: null,
        label: "إضافة موظف جديد",
        path: "/employees/add",
        level: 2,
        iconComponent: createIcon(PlusCircle),
      },
      {
        icon: null,
        label: "ضمانات الموظفين",
        path: "/employees/guarantees",
        level: 2,
        iconComponent: createIcon(ShieldEllipsis),
      },
      {
        icon: null,
        label: "كشوفات الرواتب",
        path: "/employees/salaries",
        level: 2,
        iconComponent: createIcon(FileBarChart),
      },
    ],
  },
  {
    icon: null,
    label: "الموردين",
    path: "/suppliers",
    level: 1,
    section: "الإدارة",
    permissions: ["suppliers.view"],
    iconComponent: createIcon(ShoppingCart),
    subItems: [
      {
        icon: null,
        label: "قائمة الموردين",
        path: "/suppliers",
        level: 2,
        permissions: ["suppliers.view"],
        iconComponent: createIcon(List),
      },
      {
        icon: null,
        label: "طلبيات الموردين",
        path: "/purchase-orders",
        level: 2,
        permissions: ["purchase_orders.view"],
        iconComponent: createIcon(FileText),
      },
      {
        icon: null,
        label: "حسابات الموردين",
        path: "/suppliers/accounts",
        level: 2,
        permissions: ["suppliers.view"],
        iconComponent: createIcon(FileBarChart),
      },
      {
        icon: null,
        label: "مدفوعات الموردين",
        path: "/supplier-payments",
        level: 2,
        permissions: ["supplier_payments.view"],
        iconComponent: createIcon(Receipt),
      },
    ],
  },
  {
    icon: null,
    label: "الإشعارات",
    path: "/notifications",
    level: 1,
    section: "الإدارة",
    iconComponent: createIcon(Bell),
  },
  {
    icon: null,
    label: "الفروع",
    path: "/branches",
    level: 1,
    section: "الفروع والمرافق",
    permissions: ["branches.view"],
    iconComponent: createIcon(Building2),
  },
  {
    icon: null,
    label: "الورشة",
    path: "/workshop",
    level: 1,
    iconComponent: createIcon(Wrench),
  },
  {
    icon: null,
    label: "المصنع",
    path: "/factory",
    level: 1,
    iconComponent: createIcon(Factory),
  },
  {
    icon: null,
    label: "إدارة المنتجات",
    path: "/dresses",
    level: 1,
    section: "المخزون",
    permissions: ["dresses.view"],
    iconComponent: createIcon(Package),
    subItems: [
      {
        icon: null,
        label: "قائمة المنتجات",
        path: "/dresses",
        level: 2,
        permissions: ["dresses.view"],
        iconComponent: createIcon(List),
      },
      {
        icon: null,
        label: "نقل المنتجات",
        path: "/dresses/transfer",
        level: 2,
        iconComponent: createIcon(ArrowRightLeft),
      },
      {
        icon: null,
        label: "الأقسام",
        path: "/categories",
        level: 2,
        permissions: ["dress_categories.view"],
        iconComponent: createIcon(Tags),
      },
      {
        icon: null,
        label: "الأقسام الفرعية",
        path: "/subcategories",
        level: 2,
        permissions: ["dress_categories.view"],
        iconComponent: createIcon(FolderTree),
      },
    ],
  },
  {
    icon: null,
    label: "المخزون",
    path: "/inventory",
    level: 1,
    section: "المخزون",
    iconComponent: createIcon(Package),
    subItems: [
      {
        icon: null,
        label: "نظرة عامة",
        path: "/inventory",
        level: 2,
        iconComponent: createIcon(Package),
      },
      {
        icon: null,
        label: "مخزون الفروع",
        path: "/inventory/branches",
        level: 2,
        iconComponent: createIcon(Building2),
      },
      {
        icon: null,
        label: "عمليات النقل",
        path: "/inventory/transfers",
        level: 2,
        iconComponent: createIcon(ArrowRightLeft),
      },
    ],
  },
  {
    icon: null,
    label: "التقارير",
    path: "/reports",
    level: 1,
    section: "التقارير",
    permissions: ["reports.view"],
    iconComponent: createIcon(FileBarChart),
    subItems: [
      {
        icon: null,
        label: "نظرة عامة",
        path: "/reports",
        level: 2,
        permissions: ["reports.view"],
        iconComponent: createIcon(FileBarChart),
      },
      {
        icon: null,
        label: "تقارير المبيعات",
        path: "/reports/sales",
        level: 2,
        permissions: ["reports.sales"],
        iconComponent: createIcon(BarChart3),
      },
      {
        icon: null,
        label: "تقارير الخياطة",
        path: "/reports/tailoring",
        level: 2,
        permissions: ["reports.tailoring"],
        iconComponent: createIcon(Scissors),
      },
    ],
  },
  {
    icon: null,
    label: "المحاسبة",
    path: "/accounting",
    level: 1,
    permissions: ["accounting.view"],
    iconComponent: createIcon(Calculator),
  },
  {
    icon: null,
    label: "الإعدادات",
    path: "/content",
    level: 1,
    section: "النظام",
    permissions: ["settings.profile"],
    iconComponent: createIcon(Settings),
    subItems: [
      {
        icon: null,
        label: "إدارة المحتوى",
        path: "/content",
        level: 2,
        iconComponent: createIcon(Settings),
      },
      {
        icon: null,
        label: "الملف الشخصي",
        path: "/settings/account",
        level: 2,
        permissions: ["settings.profile"],
        iconComponent: createIcon(UserCircle),
      },
      {
        icon: null,
        label: "الاشتراك",
        path: "/settings/subscription",
        level: 2,
        permissions: ["subscription.view"],
        iconComponent: createIcon(Crown),
      },
      {
        icon: null,
        label: "كيف يعمل النظام",
        path: "/how-it-works",
        level: 2,
        iconComponent: createIcon(CircleHelp),
      },
    ],
  },
];
